language: ruby
rvm:
  - 1.9.3

install:
 - gem install cucumber
 - gem install simplecov 
 - gem install coveralls 
 - gem install codeclimate-test-reporter
 
script:
  - cd bdd
  - cucumber feature/*.feature

  
