gem "codeclimate-test-reporter", group: :test, require: nil
gem 'simplecov', :require => false, :group => :test
gem 'rspec_junit_formatter', :git => 'git@github.com:circleci/rspec_junit_formatter.git'
gem 'coveralls', require: false

